// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addnumbersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _multiplynumbersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dividenumbersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerstudentMw() []app.HandlerFunc {
	// your code...
	return nil
}
