// Code generated by Kitex v0.6.2. DO NOT EDIT.

package studentservice

import (
	"context"
	management "github.com/Lortals/111cloudwego-apigateway/rpc-services/student-service/kitex_gen/student/management"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return studentServiceServiceInfo
}

var studentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "StudentService"
	handlerType := (*management.StudentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Register": kitex.NewMethodInfo(registerHandler, newStudentServiceRegisterArgs, newStudentServiceRegisterResult, false),
		"Query":    kitex.NewMethodInfo(queryHandler, newStudentServiceQueryArgs, newStudentServiceQueryResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "management",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*management.StudentServiceRegisterArgs)
	realResult := result.(*management.StudentServiceRegisterResult)
	success, err := handler.(management.StudentService).Register(ctx, realArg.Student)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStudentServiceRegisterArgs() interface{} {
	return management.NewStudentServiceRegisterArgs()
}

func newStudentServiceRegisterResult() interface{} {
	return management.NewStudentServiceRegisterResult()
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*management.StudentServiceQueryArgs)
	realResult := result.(*management.StudentServiceQueryResult)
	success, err := handler.(management.StudentService).Query(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStudentServiceQueryArgs() interface{} {
	return management.NewStudentServiceQueryArgs()
}

func newStudentServiceQueryResult() interface{} {
	return management.NewStudentServiceQueryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, student *management.Student) (r *management.RegisterResp, err error) {
	var _args management.StudentServiceRegisterArgs
	_args.Student = student
	var _result management.StudentServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Query(ctx context.Context, req *management.QueryReq) (r *management.Student, err error) {
	var _args management.StudentServiceQueryArgs
	_args.Req = req
	var _result management.StudentServiceQueryResult
	if err = p.c.Call(ctx, "Query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
