// Code generated by Kitex v0.6.1. DO NOT EDIT.

package studentmanagement

import (
	"context"
	api "github.com/ararchch/api-gateway/microservices/student_service/kitex_gen/student/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegisterStudent(ctx context.Context, req *api.RegisterStudentRequest, callOptions ...callopt.Option) (r *api.RegisterStudentResponse, err error)
	GetStudent(ctx context.Context, req *api.GetStudentRequest, callOptions ...callopt.Option) (r *api.GetStudentResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kStudentManagementClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStudentManagementClient struct {
	*kClient
}

func (p *kStudentManagementClient) RegisterStudent(ctx context.Context, req *api.RegisterStudentRequest, callOptions ...callopt.Option) (r *api.RegisterStudentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterStudent(ctx, req)
}

func (p *kStudentManagementClient) GetStudent(ctx context.Context, req *api.GetStudentRequest, callOptions ...callopt.Option) (r *api.GetStudentResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStudent(ctx, req)
}
